// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolDiary.Data;

#nullable disable

namespace SchoolDiary.Migrations
{
    [DbContext(typeof(SchoolDiaryDbContext))]
    partial class SchoolDiaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SchoolDiary.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceDate = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 2,
                            AttendanceDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 3,
                            AttendanceDate = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 4,
                            AttendanceDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = 6,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 5,
                            AttendanceDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            AttendanceDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = 4,
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("SchoolDiary.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "11-А"
                        },
                        new
                        {
                            Id = 2,
                            Name = "10-Б"
                        },
                        new
                        {
                            Id = 3,
                            Name = "9-Б"
                        },
                        new
                        {
                            Id = 4,
                            Name = "8-Б"
                        },
                        new
                        {
                            Id = 5,
                            Name = "7-A"
                        },
                        new
                        {
                            Id = 6,
                            Name = "6-A"
                        });
                });

            modelBuilder.Entity("SchoolDiary.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudentId = 1,
                            SubjectId = 5,
                            Value = 12
                        },
                        new
                        {
                            Id = 2,
                            StudentId = 2,
                            SubjectId = 4,
                            Value = 10
                        },
                        new
                        {
                            Id = 3,
                            StudentId = 1,
                            SubjectId = 1,
                            Value = 11
                        },
                        new
                        {
                            Id = 4,
                            StudentId = 2,
                            SubjectId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            StudentId = 3,
                            SubjectId = 2,
                            Value = 8
                        },
                        new
                        {
                            Id = 6,
                            StudentId = 4,
                            SubjectId = 6,
                            Value = 7
                        },
                        new
                        {
                            Id = 7,
                            StudentId = 1,
                            SubjectId = 4,
                            Value = 2
                        },
                        new
                        {
                            Id = 8,
                            StudentId = 3,
                            SubjectId = 5,
                            Value = 12
                        },
                        new
                        {
                            Id = 9,
                            StudentId = 2,
                            SubjectId = 1,
                            Value = 8
                        },
                        new
                        {
                            Id = 10,
                            StudentId = 4,
                            SubjectId = 3,
                            Value = 12
                        });
                });

            modelBuilder.Entity("SchoolDiary.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassTeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassTeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 4,
                            ClassTeacherId = 1,
                            FirstName = "Данило",
                            LastName = "Міхневич"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 4,
                            ClassTeacherId = 1,
                            FirstName = "Стас",
                            LastName = "Мікроволновка"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            ClassTeacherId = 2,
                            FirstName = "Антон",
                            LastName = "Потік"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            ClassTeacherId = 3,
                            FirstName = "Марина",
                            LastName = "Сталкер"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 1,
                            ClassTeacherId = 4,
                            FirstName = "Богдан",
                            LastName = "Компот"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 6,
                            ClassTeacherId = 2,
                            FirstName = "Софія",
                            LastName = "Роментік"
                        });
                });

            modelBuilder.Entity("SchoolDiary.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Математика",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Історія України",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Англійська мова",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Біологія",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Українська мова",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Сhemistry",
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("SchoolDiary.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Артем Стецько"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Софія Калина"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Валентин Нотатка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Олег Кернасто"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Владислав Іскра"
                        });
                });

            modelBuilder.Entity("SchoolDiary.Models.Attendance", b =>
                {
                    b.HasOne("SchoolDiary.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolDiary.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolDiary.Models.Student", b =>
                {
                    b.HasOne("SchoolDiary.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolDiary.Models.Teacher", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("ClassTeacher");
                });

            modelBuilder.Entity("SchoolDiary.Models.Subject", b =>
                {
                    b.HasOne("SchoolDiary.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
